{{- $dot := . }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ $dot.Values.prometheus.appname }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ $dot.Values.prometheus.appname }}
subjects:
- kind: ServiceAccount
  name: default
  namespace: {{ $dot.Values.prometheus.serviceaccountnamespace }}

