message:
  namespace: message
  replicas: 3
  image: "021891604918.dkr.ecr.us-west-2.amazonaws.com/message-service"
  tag: latest
  port: 5000
  imagePullPolicy: IfNotPresent

postgres:
  replicas: 1
  image: postgres
  tag: latest
  claimName: postgres-pvc
  volumeName: postgres-pv
  configmap: init-script-config
  mountPathDb: /var/lib/postgresql/data
  mountPathTable: /init
