apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: {{.Values.message.namespace}}
  annotations:
    prometheus.io/scrape: "true"
spec:
  ports:
  - port: 5432
    targetPort: 5432
  selector:
    app: postgres
