apiVersion: v1
kind: Service
metadata:
  name: message-service
  namespace: {{.Values.message.namespace}}
  annotations:
    prometheus.io/scrape: "true"
spec:
  type: ClusterIP 
  ports:
    - port: 80
      targetPort: 5000
  selector:
    name: message

