apiVersion: v1
kind: Service
metadata:
  name: message-service
  namespace: {{.Values.message.namespace}}
spec:
  type: NodePort  
  ports:
    - port: 80
      targetPort: 5000
      nodePort: 30166
  selector:
    name: message

