apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-config
  namespace: {{.Values.message.namespace}}
data:
  fluent.conf: |
    <source>
      @type tail
      path /var/log/message-app.log
      pos_file /var/log/fluentd.pos
      tag app.log
      format none
    </source>

    <match app.log>
      @type stdout
    </match>
