apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: message-service-ingress
  namespace: {{.Values.message.namespace}}
  annotations:
    kubernetes.io/ingress.class: "nginx"
  labels:
    name: message
spec:
  rules:
  - http:
      paths:
      - path: /create
        pathType: Prefix
        backend:
          service:
            name: message-service
            port:
              number: 80
      - path: /get/messages
        pathType: Prefix
        backend:
          service:
            name: message-service
            port:
              number: 80
      - path: /search
        pathType: Prefix
        backend:
          service:
            name: message-service
            port:
              number: 80
