apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: message-service-pdb
  namespace: {{.Values.message.namespace}}
spec:
  minAvailable: 1
  selector:
    matchLabels:
      name: message

