apiVersion: v1
kind: ConfigMap
metadata:
  name: init-script-config
  namespace: {{.Values.message.namespace}}
data:
  init.sql: |
    CREATE TABLE IF NOT EXISTS messages (
        account_id VARCHAR(255),
        message_id UUID PRIMARY KEY,
        sender_number VARCHAR(20),
        receiver_number VARCHAR(20)
    );

