apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: {{.Values.message.namespace}}
type: Opaque
data:
  POSTGRES_HOST: cG9zdGdyZXM=
  POSTGRES_DB: bWVzc2FnZV9kYg==
  POSTGRES_USER: dXNlcg==
  POSTGRES_PASSWORD: cGFzc3dvcmQ=

