message:
  namespace: message
  replicas: 3
  image: "message/message_service"
  tag: latest
  port: 5000
  imagePullPolicy: IfNotPresent

postgres:
  replicas: 1
  image: postgres
  tag: latest
  claimName: postgres-pvc
  volumeName: postgres-pv
  configmap: init-script-config
  mountPathDb: /var/lib/postgresql/data
  mountPathTable: /init
