apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-all-ingress
  namespace: message
spec:
  podSelector:
    matchLabels:
      name: message
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector: {}  # Allow traffic from any pod

